### ISSUE TITLE
Diffusivity and master have diverged too much

### ISSUE THREAD

**Issue by alchemyst** [GeneralTyres/pulpsim#10]
Before we do more development, we need to figure out if we still need these two branches and if so, how to merge them. At the moment they cannot be automatically merged, so take some time, merge them by hand if you feel like Diffusivity has valuable stuff in, or just delete Diffusivity and continue on master.

**Comment by alchemyst** [comment]
Once we have merged the branches, I suggest we do something [like this](http://nvie.com/posts/a-successful-git-branching-model/). The idea is that `master` is always runnable and stable, and that `develop` is used to develop new bits. One should try to avoid getting to the state where the branches aren't mergable anymore.

**Comment by GeneralTyres** [comment]
I think we can delete Diffusivity. The only real difference is the function for the diffusivity constants. That function is short and can be quickly integrated in the master branch. It will be to much effort to try and merge them.

**Comment by GeneralTyres** [comment]
The git branching model looks like a good implementation. Will create a develop branch now.
