### ISSUE TITLE
Rename components

### ISSUE THREAD

**Issue by alchemyst** [GeneralTyres/pulpsim#4]
The component names are at the moment just A, B and C. This should be renamed to be the correct names of the components we're simulating.

**Comment by GeneralTyres** [comment]
I renamed the components to Lignin, Carbohydrates, Alkali and Sulfur. There isn't a rate expression for sulfur as it is assumed the concentration stays the same. When the Andersson model is used the lignin and carbohydrates will then be further divided into three species each. Probably need to think of how that's going to work.
