### ISSUE TITLE
Use a dictionary or a namedtuple for parameters

### ISSUE THREAD

**Issue by alchemyst** [GeneralTyres/pulpsim#8]
At the moment we are using a vector and expansion for parameters, i.e.

    a, b, c = [1, 2, 3]
    formula = a + b + c

It would be more generic to use a dictionary

    parameters = {'a': 1, 'b': 2, 'c': 3}
    formula = parameters['a'] + parameters['b'] + parameters['c']

or a `namedtuple`

    import collections
    Parameters = collections.namedtuple('Parameters', 'a b c')
    parameters = Parameters(1, 2, 3)
    formula = parameters.a + parameters.b + parameters.c

**Comment by GeneralTyres** [comment]
I made a new commit in my master branch. In it I modified the reader function. The commit description gives more details. I think this is more-or-less the way we discussed the data should be handled. Please review and then I’ll do a pull request.

**Comment by alchemyst** [comment]
Excellent. That's pretty much what I had in mind. PS, if you put a commit number like this a399180b6be890c4fe87aa06c86ecaf071614252 in a comment, it will link to that commit. You can also reference issues like #8 this in commit messages. (So you could say something like "Fixed #8" in there and it will link here).
